export function createBoard(){
    return `
    <div class="grid grid-cols-8 border-double border-amber-900 border-[2px] w-[400px] h-[400px]">
        <div class="light-square tile" id="a8"></div> <div class="dark-square tile" id="b8"></div> <div class="light-square tile" id="c8"></div> <div class="dark-square tile" id="d8"></div> <div class="light-square tile" id="e8"></div> <div class="dark-square tile" id="f8"></div> <div class="light-square tile" id="g8"></div> <div class="dark-square tile" id="h8"></div>
        <div class="dark-square tile" id="a7"></div> <div class="light-square tile" id="b7"></div> <div class="dark-square tile" id="c7"></div> <div class="light-square tile" id="d7"></div> <div class="dark-square tile" id="e7"></div> <div class="light-square tile" id="f7"></div> <div class="dark-square tile" id="g7"></div> <div class="light-square tile" id="h7"></div>
        <div class="light-square tile" id="a6"></div> <div class="dark-square tile" id="b6"></div> <div class="light-square tile" id="c6"></div> <div class="dark-square tile" id="d6"></div> <div class="light-square tile" id="e6"></div> <div class="dark-square tile" id="f6"></div> <div class="light-square tile" id="g6"></div> <div class="dark-square tile" id="h6"></div>
        <div class="dark-square tile" id="a5"></div> <div class="light-square tile" id="b5"></div> <div class="dark-square tile" id="c5"></div> <div class="light-square tile" id="d5"></div> <div class="dark-square tile" id="e5"></div> <div class="light-square tile" id="f5"></div> <div class="dark-square tile" id="g5"></div> <div class="light-square tile" id="h5"></div>
        <div class="light-square tile" id="a4"></div> <div class="dark-square tile" id="b4"></div> <div class="light-square tile" id="c4"></div> <div class="dark-square tile" id="d4"></div> <div class="light-square tile" id="e4"></div> <div class="dark-square tile" id="f4"></div> <div class="light-square tile" id="g4"></div> <div class="dark-square tile" id="h4"></div>
        <div class="dark-square tile" id="a3"></div> <div class="light-square tile" id="b3"></div> <div class="dark-square tile" id="c3"></div> <div class="light-square tile" id="d3"></div> <div class="dark-square tile" id="e3"></div> <div class="light-square tile" id="f3"></div> <div class="dark-square tile" id="g3"></div> <div class="light-square tile" id="h3"></div>
        <div class="light-square tile" id="a2"></div> <div class="dark-square tile" id="b2"></div> <div class="light-square tile" id="c2"></div> <div class="dark-square tile" id="d2"></div> <div class="light-square tile" id="e2"></div> <div class="dark-square tile" id="f2"></div> <div class="light-square tile" id="g2"></div> <div class="dark-square tile" id="h2"></div>
        <div class="dark-square tile" id="a1"></div> <div class="light-square tile" id="b1"></div> <div class="dark-square tile" id="c1"></div> <div class="light-square tile" id="d1"></div> <div class="dark-square tile" id="e1"></div> <div class="light-square tile" id="f1"></div> <div class="dark-square tile" id="g1"></div> <div class="light-square tile" id="h1"></div>
    </div>
    `
}