export function createBoard(){
    return `
    <div id="board" class="grid grid-cols-8 border-double border-amber-900 border-[2px] w-[400px] h-[400px]">
        <div class="light-square tile" id="00"></div>   <div class="dark-square tile" id="01"></div>    <div class="light-square tile" id="02"></div>   <div class="dark-square tile" id="03"></div>    <div class="light-square tile" id="04"></div>   <div class="dark-square tile" id="05"></div>    <div class="light-square tile" id="06"></div>   <div class="dark-square tile" id="07"></div>
        <div class="dark-square tile" id="10"></div>    <div class="light-square tile" id="11"></div>   <div class="dark-square tile" id="12"></div>    <div class="light-square tile" id="13"></div>    <div class="dark-square tile" id="14"></div>    <div class="light-square tile" id="15"></div>   <div class="dark-square tile" id="16"></div>    <div class="light-square tile" id="17"></div>
        <div class="light-square tile" id="20"></div>   <div class="dark-square tile" id="21"></div>    <div class="light-square tile" id="22"></div>   <div class="dark-square tile" id="23"></div>    <div class="light-square tile" id="24"></div>   <div class="dark-square tile" id="25"></div>    <div class="light-square tile" id="26"></div>   <div class="dark-square tile" id="27"></div>
        <div class="dark-square tile" id="30"></div>    <div class="light-square tile" id="31"></div>   <div class="dark-square tile" id="32"></div>    <div class="light-square tile" id="33"></div>   <div class="dark-square tile" id="34"></div>    <div class="light-square tile" id="35"></div>   <div class="dark-square tile" id="36"></div>    <div class="light-square tile" id="37"></div>
        <div class="light-square tile" id="40"></div>   <div class="dark-square tile" id="41"></div>    <div class="light-square tile" id="42"></div>   <div class="dark-square tile" id="43"></div>    <div class="light-square tile" id="44"></div>   <div class="dark-square tile" id="45"></div>    <div class="light-square tile" id="46"></div>   <div class="dark-square tile" id="47"></div>
        <div class="dark-square tile" id="50"></div>    <div class="light-square tile" id="51"></div>   <div class="dark-square tile" id="52"></div>    <div class="light-square tile" id="53"></div>   <div class="dark-square tile" id="54"></div>    <div class="light-square tile" id="55"></div>   <div class="dark-square tile" id="56"></div>    <div class="light-square tile" id="57"></div>
        <div class="light-square tile" id="60"></div>   <div class="dark-square tile" id="61"></div>    <div class="light-square tile" id="62"></div>   <div class="dark-square tile" id="63"></div>    <div class="light-square tile" id="64"></div>   <div class="dark-square tile" id="65"></div>    <div class="light-square tile" id="66"></div>   <div class="dark-square tile" id="67"></div>
        <div class="dark-square tile" id="70"></div>    <div class="light-square tile" id="71"></div>   <div class="dark-square tile" id="72"></div>    <div class="light-square tile" id="73"></div>   <div class="dark-square tile" id="74"></div>    <div class="light-square tile" id="75"></div>   <div class="dark-square tile" id="76"></div>    <div class="light-square tile" id="77"></div>
    </div>
    `
}